global:
  # How frequently to scrape targets by default.
  # Default 15s
  scrape_interval: 1s
  # How frequently to evaluate rules.
  # Default 15s
  evaluation_interval: 1s
  # How long until a scrape request times out.
  # Default to 10s.
  # Required because cp-demo is using cpu throttling, so let's leave enough time to fetch the metrics in particular for the first time as it needs to compile all rexps
  scrape_timeout: 1s

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: cadvisor
    static_configs:
    - targets: ["cadvisor:8080"]

  - job_name: "docker"
    static_configs:
      - targets: ["172.19.0.1:9323"]

  - job_name: 'netflix-zuul-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.206.57:8081']

  - job_name: 'spring-cloud-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.206.57:8082']

  - job_name: 'fast-rest-service-v0'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.206.57:8180']

  - job_name: 'fast-rest-service-v1'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.206.57:8181']

  - job_name: 'slow-rest-service-v0'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.206.57:8280']

  - job_name: 'slow-rest-service-v1'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.206.57:8281']